name: 'Contributor Report'
description:
  'Analyze PR contributors and generate detailed quality reports using GitHub metrics - Combat AI-generated spam and
  slop code'
author: 'jdiegosierra'

branding:
  icon: 'user-check'
  color: 'blue'

inputs:
  github-token:
    description: 'GitHub token for API access'
    required: true
    default: ${{ github.token }}

  thresholds:
    description: 'JSON object with custom metric thresholds'
    required: false
    default: '{}'

  threshold-pr-merge-rate:
    description: 'Minimum PR merge rate (0-1)'
    required: false

  threshold-account-age:
    description: 'Minimum account age in days'
    required: false

  threshold-positive-reactions:
    description: 'Minimum positive reactions required'
    required: false

  threshold-negative-reactions:
    description: 'Maximum negative reactions allowed'
    required: false

  threshold-merger-diversity:
    description: 'Minimum number of unique maintainers who merged PRs'
    required: false

  threshold-repo-history-merge-rate:
    description: 'Minimum merge rate in this specific repository (0-1)'
    required: false

  threshold-repo-history-min-prs:
    description: 'Minimum number of previous PRs in this repository'
    required: false

  threshold-profile-completeness:
    description: 'Minimum profile completeness score (0-100)'
    required: false

  enable-spam-detection:
    description: 'Enable suspicious activity pattern detection'
    required: false
    default: 'true'

  required-metrics:
    description: 'Comma-separated list of metrics that must pass'
    required: false
    default: 'prMergeRate,accountAge'

  minimum-stars:
    description: 'Minimum stars for a repo to be considered quality'
    required: false
    default: '100'

  analysis-window:
    description: 'Months of history to analyze'
    required: false
    default: '12'

  trusted-users:
    description: 'Comma-separated list of usernames to always pass'
    required: false
    default: 'dependabot[bot],renovate[bot],github-actions[bot],codecov[bot],sonarcloud[bot]'

  trusted-orgs:
    description: 'Comma-separated list of organizations whose members always pass'
    required: false
    default: ''

  on-fail:
    description: 'Action when check fails: comment, label, fail, comment-and-label, none'
    required: false
    default: 'comment'

  label-name:
    description: 'Label to apply when on-fail includes label'
    required: false
    default: 'needs-review'

  dry-run:
    description: 'Log results without taking action'
    required: false
    default: 'false'

  new-account-action:
    description: 'Behavior for accounts younger than threshold: neutral, require-review, block'
    required: false
    default: 'neutral'

  new-account-threshold-days:
    description: 'Days to consider an account as new'
    required: false
    default: '30'

outputs:
  passed:
    description: 'Whether all required metrics passed their thresholds'

  passed-count:
    description: 'Number of metrics that passed'

  total-metrics:
    description: 'Total number of metrics evaluated'

  breakdown:
    description: 'JSON breakdown of individual metric results'

  recommendations:
    description: 'JSON array of recommendations for the contributor'

  is-new-account:
    description: 'Whether the account is less than the threshold days old'

  has-limited-data:
    description: 'Whether there was limited data for analysis'

  was-whitelisted:
    description: 'Whether the user was on the trusted list'

runs:
  using: 'node20'
  main: 'dist/index.js'
